sudo: false
language: java
jdk: oraclejdk8

script:
- "./gradlew test"

after_success:
- mv build/distributions/nspek-integration-*.zip build/distributions/nspek-integration.zip
- test "$TRAVIS_BRANCH" == "master" && ./gradlew publishPlugin -PpublishChannel=Stable

env:
  global:
  - secure: T+yJtMPFKK3gxyq/SE0BMNDC+UoOAl5JNL9lch1p2+N0j3J/4iAO5AY9QwHxWfMMZjT4bUKo4VR1+FQARa8YDKzwgXjZM1Hh88R25QJA+Dvlovgb2kTtFq6+Bt+LFiv7D2SUkoj42lLDGsKifdFSYUH0cwEeSfD2eGIujsYQqhAF7j3Nbb4YHsYiK2wz2WtyyVDwgx00R8d6ggkAFUfGx3F+r3xwO5OwgF8hqCxom/06MlR424HQwTCguYF+JXP6VkRYNnw6DmqY9RnDo4ODUlVoiKu5sqZS91hfmDb0N1AviBg98tVEcr15OCfC0zvCX9RxpT9OsAx9vgXdaX1BZX7OrKsyvJ9tZeCdtB57kpqR0eNe31jMLelCsgix0HHY/Pjjf8t19yedctJwOftSNKxM8pKnqVtA+Ku9eDNg4wQ5yKCrHyPuqLwQ70bA+x35FIh9gGhOv1dZpNJytw4k/jsdaC0FxPJOoytIbn0LoPPH5G5DJbjvkgqUL322cVsUHgeNneSqdKukkUn0tUHnlEKKpBWk6S/nPxRPT8Brml0sT9g0kPsIQxoOjOnTA8VdtJ/5DM+bIbmM+n2MIUiizKu/P/5SExTQ9ufAVxPLO05dYpTzlfM9DQSTKdcKk3j0qqxhy7JIgXFFvfMvHARegrHkclWznCTLFn0jBFTRj3I=
  - secure: u5GnGQyzDzZczlSuiHlp2yOUU7b+22rAS3KKQI4SbXORogD+/1/jr/h4PUP4NYSTVE2PKOgnhVIJqzqbWAD84+UNRJE7rdaFPTRz5qn6D934m3vn7vHs+QOveq7PfB0yMrdmRaIY4CBFyFzGbVBAE3AfuMg5sPPJplqgM2djMjHMEYy4JmpjBba9yWD2rNPcga3aXtu0Aix3RaJBMvI07xIzeq5ztD2XEDrxbrOyt9NuZsgv0f6bNqRfFYWjOV4uepTtWZrcDkT3Xt4nOQf+N2wRfVGPN4GYBah57uskTedptpVCB52o0Wofqrsty51Q/FZmCgr//zbxhEFdRVyIVUPHjcU0KNa6LNCXzECq2VvleGlmlVhqcsofV8ZoXZjzfyXGvZjvkfY1c8I2YMOSbXSB/nJ5paoqlk/074CIx/42zhOkyCD51IJs66iMK98DrbFeJuy2IbU3NTOdIXkpALCkvS/m+ZqEffOjX1FRA11L80frR26pemv5FdUx/1D9e8ZDKDziDm1vP5GBOwofQE3NsveHyG1u4eWpqHcy6q/LK8QZ1B+ovd5yErWoCEBG6bCWEc9KGjeOUJ6XvF5iNjCbXQLCUeA/Mj5rbEqSxlewdoKmrr3NGbRd6p4i4dKMvZKfGeJNkyPAw506kJ8WjCn6KEVh6/tmKlCWtWPoiXU=

deploy:
  provider: releases
  api_key:
    secure: vlqCAslQNmJEixntWV0m/kfn/tRd+O0mhSTBTAbJ1WTXxNSC2Pvzm5GS4Mc/Z76ljZmtohxFzhombpw8HcIECO158W6CnCjBwa9jUPR5YIgoUZYt4x5oF7VRkhi6K/9b2pJoYcOhSHHrbnEl+MNXhMNOEUyWgfiEa50YVXpuOLGKZxsk1RI5m5Cddh+p4KGYpgNGHpRvAw5VZkRzjkXe9AwNHOEiltUynmq0PQL6KwBC+5r8AOqYodQvYZ2hdTPhrPS0AvmLNFgCj6t8phzf9b/5uJRodHKJq8jCwIbZkDTjawBoLuPqNvCaWLMaZh959wyqPGd20Jt7QkAO8bOESOvaWfQLWDaSBUKFBye/MUmEuT0d9FKKgKEOt+06P2qjo51ja5HU64M0cgoFywEgT9ZK3YY4xnkXMqLU6XcJXtmskm4VFHwfHGvcPbaFsfOKK6FpJ/I3p2AWNqIHdjkSnB556HW50mEqlTxmdJzNkOzMEjx6TehoUqZdlJlKCt1S4yvpqZ0J+lK6xnJkIuR3M/7TH692oh3ktU09HvRCn60L2OvODaiY98NK/70H1bXx/jf0NkTclTO8IDrgA/xNDrJN7z2YS6EhupCOXWE2hAIUiWkX4G5+BqKTMy663chiLqQFrK211EQI1r/ms79G4P4XtQs+FXHvN8t9ff3qT4Y=
  file: build/distributions/nspek-integration.zip
  skip_cleanup: true
  on:
    repo: ghostbuster91/nspek-intellij-plugin
    branch: master
