sudo: false
language: java
jdk: oraclejdk8

script:
- "./gradlew test"

after_success:
- mv build/distributions/nspek-integration-*.zip build/distributions/nspek-integration.zip
- test "$TRAVIS_BRANCH" == "master" && ./gradlew publishPlugin

env:
  global:
  - secure: Rwp4WmrPRL/3bE13nePFoN0kwNTnGc6AdKmZAnG+6st7IQMMoxcWkLaeXr6+5eJ6C3ZSb05O1dTluoPQ8E8+IJfRSI4AkNDxRjNV1EuMQJInT+mmVn6QzZ80L4NRMSZW8eJWBxtzQoy8kshFatK6+7eHUHCLC9blY9kIMM6lAagGeUxcYbnieKbS0x4YvIfAUCjPh3OxmoPB0gNhtWJb/dCJCLmNTuYRevBz9ORgsRcCJ/GDHdrYRasfH9L5WM9odotvnz8L/7zkWc83WjgLQc+IF8LE7VDF0RHO8nVfQiOrSJAHXxcuT4P89aCuEtWZApAJgCeuvZzANOEj6ThNG1rvZCdQmmaywvLMvahLYiuxwS5Ow661cqfV0nn5uyE6Yl/RHGa/KJkrXZYGm7JEynA9dLYnrXMKKeB6IEqLcPcvFhBbwZNYIlIhmgeXWLmxmsLW41hWWC8bgeAapz+omvKqO3uV1DMzfxX0GwY4beigHgg3pBuDGiizTkbzH6ZzB4bN5RgDARGC5pVNdSrGVXRE32ZzhyjJC1D5ZUbBWf0VvOrMwNsCbNSkQIyLPEW0vwvSry/d6QXfjL7IV2cMTu+F0M7/nyOiQHfR+MfM5JZ+wINv2bbe/i5Hl9UVJP8TpY+ZILczAh7I2guDaIVBZZ/NLusyG5iKlQyGmpUJL+M=
  - secure: dszTNafV19fh3U+YIwHpGLNS8LrQbhRSQCClXE4jNt0ODxR6Yl+Y45McM+qG5K5veEGJRcEZsCIaZ1++IR8VRLHYj/nNlFWpJdRV5WJjNbDzEBoNH+fIFSyHVwK2xDjllRVyTD8imBWX2w+NK0v6SE3g8TmVFY0ykboRX+tIvHahbVFDVYP9fxXzk6KdGbZKopguXD13485oXu48XoeB+PHQEQDDTk6b30cViyygtp0BPHYpwOEBtalhTMlSOr6oG0Ff22mEBZ2RwZ0xSkrWbP9xf/9X73HbTO94ijXmRssOQWCzmnRD6r72DY3MjFEY4tI4pBGLbyc0BYHByvVC1UvypLa0whL6vX1BW3QmlucTV3H2q6gwdBziLWkqzNQA6hmwmLvlMbEe+hz0XhCCH0GPvwA7+n1IRmDpMm7np1uQOKUfGxC6RnIYIAXT4X8ues4KVR5Rgb7HRFNli3FNou/qNk70XAONmMkwUxSy3nV+JRdwmGayURYs2zhVqL584zIwvFpaKlhr+0HNANeuM6AoMn2/HHmJuLK6qzQnkchsQ+XoGesGnqHFhWtT1eZQfGEtNOWqdEleBRBkH4qIaZi91Wpwr3dovUDF2YNSJIGhhnn/FjwxV11D9cqsEaH6S4m/SpDWj2ym0xYT8/4xy5gl7p9CsKu1kG8k/HGtsM4=

deploy:
  provider: releases
  api_key:
    secure: BKJeLq6tx84WQDel8uMZAvLxWjygX6KVzyrjy/h8PLPWUPYHI7WHJoeo5qEZn6+xI6vRiohDP1OnKS3eOQEsV36xZWW2IGYjK7KN5LEkmPp6hGj8LlK2f+NO/4/XA0RHxay+sdy3lrTNJH5v769ZKUIP/T6kxquSRVBO4sI9qeUbDHk/kxLZMksFBmJiiv1OJXS/Da5DMZXVBejRibCK6WFLTJZyKaEWhAnNub5w3p2Q6eG1OYPWF3fz//wR4WYDCC4mo2FsMTwdMLlTu/mlSjOQ6CY/MBB3hGAj9SYqPLdY+y2pk36TNWoMHErCkxLBV0MjsmRsi5w0N2RNx5L0Bf+1gNkZYw/fF5W3nWrMOg5Uqi8JRPtA3bnM3+V0e6mX9AbIHQso5KqmTNWVzGBiI6FQ6fULL+d1SNv+NoVmfyCfUT1cpZXxDiSrxBll35dtabZnSrx2xEgwqXnixlrkbJDShGDZSDbjko59Lu5wZYylLtzHMpUEHrGcNGlle+QpjptoWa8StO1Llq3JWgkdBJ0zZWaiX28mZhMGhv1sldRw0ZgaS8tHB8LiuFxTv+NwTRY80Ztm9Yd5kTPJR12Ow9BS+cjW81tTvjDlWQXUb4Uoor6+7Ast3EvU/kf8WhBtCoiXj0CEzkDV6gajKGYPyENd2wn7vFNFTcoNSd2rTp0=
  file: build/distributions/nspek-integration.zip
  skip_cleanup: true
  on:
    repo: ghostbuster91/nspek-intellij-plugin
    branch: master